In [12]:
import numpy as np

#Single dimentational array
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [14]:
#Two-dimentatinal array
sec = np.array([[2.3, 1.0, 4.4], [2.2, 8.9, 9.0]])
print(sec)

[[2.3 1.  4.4]
 [2.2 8.9 9. ]]


In [15]:
#Get the dimention of the array
print(arr.ndim)
print(sec.ndim)

1
2


In [16]:
#Print array shap of array, liken n*m 
print(sec.shape)

(2, 3)


In [28]:
#3-dimention array
c = np.array([  [[1, 2], [3, 4], [5,6]], [[7, 8], [9, 10], [11, 12]] ])
d = np.array([ [['a', 'b'], ['c', 'd'], ['e', 'f']], [['g', 'h'], ['i', 'j'], ['k', 'l']]  ])
e = np.array([ [ [11, 22, 33], [44, 55, 66] ], [[77, 88, 99], [111, 222, 333]] ])

print(c)
print(c.ndim)
print(c.shape)


print('===============')
print(d)
print(d.ndim)
print(d.shape)


print(e)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)
[[['a' 'b']
  ['c' 'd']
  ['e' 'f']]

 [['g' 'h']
  ['i' 'j']
  ['k' 'l']]]
3
(2, 3, 2)
[[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [111 222 333]]]


In [33]:
#Get array datatype
print(c.dtype)
print(d.dtype)
print(e.dtype)

int32
<U1
int32


In [37]:
#We can also specify the dtype for array

k = np.array([1, 2, 3], dtype='int32')
print(k.dtype)


int32


In [50]:
#Get Number of elements in array
print(k.size)
print(d.size)

3
12


In [49]:
#Get size of each elememnt
print(k.itemsize)
print(sec.itemsize)
print(d.itemsize)

4
8
4


In [48]:
#Get total size of array
print(k.nbytes)
print(sec.nbytes)
print(d.nbytes)

12
48
48


###### Accessing array elements

In [63]:
a = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 19, 11, 12]], dtype='int32')
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print("========")

#accessing
print(a[1][1])
print(a[0][4])
print(a[1][-1])
print(a[-1][-1])

#We can also access as below , Which is more prefered.
print('---------------')
print(a[1, 1])
print(a[0, 4])
print(a[1, -1])
print(a[-1, -1])




[[ 1  2  3  4  5  6]
 [ 7  8  9 19 11 12]]
2
(2, 6)
12
int32
4
48
8
5
12
12
---------------
8
5
12
12


In [68]:
#Get row wise

print(a[0])
print(a[-1])

#We can also get as bellow
print('=============')
print(a[0, :])
print(a[1, :])

[1 2 3 4 5 6]
[ 7  8  9 19 11 12]
[1 2 3 4 5 6]
[ 7  8  9 19 11 12]


In [72]:
#Get colum wise
#print(a[][0]) Not possible
print(a)
print(a[:, 0])
print(a[:, 4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 19 11 12]]
[1 7]
[ 5 11]


In [75]:
#access randomly
print(a)
#In below array extract ele from 2 to 5
# array[row, startidx:endidx:step]

print(a[0, 1:5:1])


[[ 1  2  3  4  5  6]
 [ 7  8  9 19 11 12]]
[2 3 4 5]


In [81]:
#Change the 4 to 44
a[0, 3] = 44
print(a)

#Now change entier first row into 44
a[0, :] = 44
print(a)

#Now change second coulm to 88
a[:, 1] = 88
print(a)

#Now change thrid colum into 111 and 222
a[:, 2] = [111, 222]
print(a)

[[ 44  88 111  44  44  44]
 [  7  88 222  19  11  12]]
[[ 44  44  44  44  44  44]
 [  7  88 222  19  11  12]]
[[ 44  88  44  44  44  44]
 [  7  88 222  19  11  12]]
[[ 44  88 111  44  44  44]
 [  7  88 222  19  11  12]]


In [97]:
#Accessing three-dimenstonal array
b = np.array([ [ [1,2], [3, 4] ], [[5, 6], [7, 8]]])
print(b)
print(b.ndim)
print(b.size)
print(b.itemsize)
print(b.dtype)
print(b.nbytes)
print('=======')

#access value 4 in below array
b[0, 1, 1]

#Access value 6
b[1, 0, 1]

#Print second two-dimenstional array
print(b[1, :, :])
#or we can use like this as well
print(b[1])

#Print second two-d array first row
print(b[1, 0, :])

#print 2 and 4
print(b[0, :, 1])


#Replecae second two -d array
b[1,:, :] = [[11, 11], [22, 22]]
print(b)




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
8
4
int32
32
[[5 6]
 [7 8]]
[[5 6]
 [7 8]]
[5 6]
[2 4]
[[[ 1  2]
  [ 3  4]]

 [[11 11]
  [22 22]]]


###### Initialize the array

In [129]:
#Create two-dimentonal array with zero initalized 
#Pass the shap of two-dimentonal array
c = np.zeros((2,2))
print(c)

d = np.zeros((1,3,3))
print(d)

e = np.zeros((1))
print(e)

#Initalize 2*3*4 array with 'one' and dtype is int32
f = np.ones((2, 3, 4), dtype='int32')
print(f)

#initalize arry with other than zero and one using 'full' method
#Initialize array with 99
g = np.full((2,3), 99, dtype='int16')
print(g)


#full_like simillor to full, but it use the existing array to create new one
#Below example create h array which is simllor to array g shape, but all the elements in h is intiaized to -1
h = np.full_like(g, -1)
print(h)

#Now intilize 2*3 matrics with random number

i = np.random.rand(2, 3)
print(i)

#create array simillor to i shape , but initalized with random number which are different from i array elements.
j = np.random.random_sample(i.shape)

print(j)

#Initialize random integer value range from 7 to 8 (9-1)for 3*3 array
# if high here 9 is not specified then low value 7 itself is consider to be highest value.
k = np.random.randint(7, 9, size=(3,3))
print(k)

#Here value goes at max 9, since high is not specified.
l = np.random.randint(low=9, size=(3,3))
print(l)

[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[99 99 99]
 [99 99 99]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[0.68456234 0.80133347 0.67934366]
 [0.51806356 0.19003862 0.64266256]]
[[0.3288931  0.34408147 0.86332055]
 [0.17396191 0.43284998 0.92305576]]
[[8 8 7]
 [7 7 8]
 [8 7 7]]
[[2 0 0]
 [3 3 1]
 [0 1 6]]


###### Create a identtity matrix.


In [132]:
#Identity matrix is squre matrix.
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [149]:
#Repeate the array by 3 times
a = np.array([1, 2, 3])
b = np.repeat(a, 3)
print(b)

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.repeat(c, 3)
print(d)

#axis = 1 is will thorugh error. 
b = np.repeat(a, 3, axis=0)
print(b)

d = np.repeat(c, 3, axis=0)
print(d)

d = np.repeat(c, 3, axis=1)
print(d)

[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]
[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [156]:
#Craete a array shape is 5*5 with outer most layer contins 1's and second outer most layer contins 0's and middle one ele contain 9

output = np.ones((5, 5))
print(output)

#Now create tmp array with 3*3
tmp = np.zeros((3, 3))
print(tmp)

tmp[1,1] = 9
print(tmp)

#Now replace inner layers of output array with tmp array
output[1:-1, 1:-1] = tmp

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be carefull of while copying array

In [160]:
a = np.array([1, 2, 3, 4])
# b array is also pointing to array a, Basically both are same memory location.
b = a
b[0] = 1111
print(a)
print(b)

c = np.array([1, 2, 3])
print(c)
#This create new copy of array in different memory location for d array
d = c.copy()
d[0] = -999
print(c)
print(d)


[1111    2    3    4]
[1111    2    3    4]
[1 2 3]
[1 2 3]
[-999    2    3]


###### Mathematics

In [169]:
a = np.array([1, 2, 3, 4])
print(a)

print(a + 2)
print(a-1)
print(a*2)
print(a/2)
print(a.itemsize)
a = a/2
print(a)
print(a.itemsize)

[1 2 3 4]
[3 4 5 6]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
4
[0.5 1.  1.5 2. ]
8


In [173]:
a = np.array([1,2,3])
print(a)

a +=2
print(a)
a -=2
print(a)

[1 2 3]
[3 4 5]
[1 2 3]


In [181]:
#Add two array

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

print('-----')
c = np.array([11, 22])

#Both array should have same shape. Hence below addtion will give error.
#print(a+c)


[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]
-----


In [183]:
#Power to 2

a = np.array([1, 2, 3])
a **= 2
print(a)


[1 4 9]


In [185]:
#Take sin and cos (trigonometry funtions) of all the array elemnents
a = np.array([1, 2, 3])
print(np.sin(a))

print(np.cos(a))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


###### Linear algebra

In [191]:
a = np.ones((2,3))
b = np.full((3, 2), 2)
print(a)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [200]:
#Find the determind
c = np.identity(3)
d = np.random.randint(3, 7, size=(3,3))
print(np.linalg.det(c))
print(d)
print(np.linalg.det(d))

1.0
[[3 4 5]
 [3 4 6]
 [3 6 6]]
-6.0


###### Statstics


In [212]:
#Note:
# axis = 0 ==> cloumswise
# axis = 1  ==> rowwise

a = np.array([[1, 2, 3], [4, 5, 6]])
#Min in matrix
print(np.min(a))

#Max in matrix
print(np.max(a))
print(a)

print('--------')
#Max in each row
print(np.max(a, axis=1))

#Min in each row
print(np.min(a, axis=1))
print('-------')

#Max in each colum
print(np.max(a, axis=0))
print(np.min(a, axis=0))

1
6
[[1 2 3]
 [4 5 6]]
--------
[3 6]
[1 4]
-------
[4 5 6]
[1 2 3]


###### Reorginzing array

In [219]:
a = np.array([[1,2, 3, 4, 5, 6], [7, 8, 9, 11, 12, 13]])
print(a.shape)
print(a)

b = a.reshape(2,3, 2)
print(b)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 11 12 13]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 11]
  [12 13]]]


In [244]:
#Vertically stacking array
#No. of colums should be same
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1,v2]))

print(np.vstack([v2, v1, v1, v2, v2]))

print('======')
v3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
v4 = np.array([11,12, 13, 14])
print(np.vstack([v4,v3]))




[[1 2 3 4]
 [5 6 7 8]]
[[5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[11 12 13 14]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [245]:
#Horizntal stacking
#No of rows should be same
h1 = np.array([1, 2, 3, 4])
h2 = np.array([5, 6, 7, 8])

print(np.hstack([h1, h2]))

h3 = np.array([1, 2, 3])
h4 = np.array([11, 12, 13, 14])

print(np.hstack([h3, h4]))

[1 2 3 4 5 6 7 8]
[ 1  2  3 11 12 13 14]


### Load a data from File

In [257]:
#Load the file
filedata = np.genfromtxt('num.txt', delimiter=',')
print(filedata)
output = filedata.astype('int32')
print(output)


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


###### Boolean masking and Advance indexing

In [262]:
print(output)
#Gneratate new array with flase or true based on the condition 
output > 50

#If we want speatae list which is having value > 50
print(output[output > 50])


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[196  75 766  75  55 999  78  76  88]


In [265]:
#You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
#Now print values in index 1,2 and 8
print(a[[1, 2, 8]])


[1 2 3 4 5 6 7 8 9]
[2 3 9]


In [276]:
print(output)
#print out if any colums in below array contins value > 50

print(np.any(output > 50, axis=0))

#print out if any of the rows contias values > 50
print(np.any(output > 50, axis =1))

print('--------------')
print((output> 50) & (output < 100))
print(~(output > 50) & (output < 100))


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[ True  True  True]
--------------
[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[[ True  True  True  True False False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False  True  True  True False  True 

In [296]:
#How to print diganal or zig-szag elements
e = np.array([ [11, 22, 33, 44], [44, 55, 66, 77] , [111, 88, 99, 199], [121, 222, 333, 999]] )
print(e)

# print 22,66,199
print(e[[0, 1, 2], [1, 2, 3]])

print(e[ [0, 2, 3], 2: ])



[[ 11  22  33  44]
 [ 44  55  66  77]
 [111  88  99 199]
 [121 222 333 999]]
[ 22  66 199]
[[ 33  44]
 [ 99 199]
 [333 999]]
